### ISSUE TITLE
Parallel generation not actually working in parallel

### ISSUE THREAD

**Issue by Anaerin** [GeheimagentNr1/WorldPreGenerator#10]
**Versions**
Minecraft Version: 1.18.6
Minecraft Forge Version: 40.1.20
Mod Version: 2.0.1

**Log files**
N/A

**Describe the bug**
Despite parallel being enabled and count set to 10 (to allow some threads for the server to run), chunks aren't being generated in parallel - only a single thread is being used - CPU usage is only 180% (rather than the 1000% it should be) and it's generating 1 chunk per second.

**Expected behaviour**
The server should be using multiple threads on multiple CPUs to generate chunks in the background, rather than doing it all on the main thread.

**Additional context**
Using Moonlit Myths modpack.

**Comment by Anaerin** [comment]
Nothing? Anybody?

**Comment by GeheimagentNr1** [comment]
The pre generation algorithm is using the Vanilla Minecraft way to generate chunks. And the Vanilla generation forces itself to always use the main thread.
I am currently refactoring the parallel pre generation, but it will use the Vanilla Minecraft generation mechanism after all.
