### ISSUE TITLE
Chunks are not saving after pausing and resuming

### ISSUE THREAD

**Issue by chocobear01** [GeheimagentNr1/WorldPreGenerator#11]
**Versions**
Minecraft Version: 1.16.5
Minecraft Forge Version: 0.200.1.7
Mod Version: 2.0.0

**Log files**
Please append the log, debug-log and if available the crash-log files.

**Describe the bug**
This mod works great for me until I need to pause and resume  pregeneration in a modded minecraft world (mod specifics are described in the steps below) or exit and re-enter the modded world. When I do, the average chunk generation rate jumps from 15 to 200 and chunk files are no longer being saved in the region folder for the world.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a 1.16.5 minecraft world using the Medieval Minecraft Modpack with the Untamed Wilds and 3d Skin Layers mods removed and Epic Fight mod added.
2. Run a command to pregenerate any amount from the chat.
3. Check that chunk files be uploaded to your Region folder for the world.
4. Use the /pregen pause command to pause pregeneration after any amount of chunks has been generated. 
5. Use the /pregen resume command to resume pregeneration.
6. Check the in-game chat log and region folder.

**Expected behaviour**
I would assume upon resuming pregeneration that it would continue saving chunk files and stay at the same rate.

**Additional context**
I have tested this by running /pregen pause followed by /pregen resume, running /pregen pause, exiting the world, entering the world, and running /pregen resume, and exiting and entering the world without running the commands, but had the exact same results each time.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Further information requested</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>tba</td></tr><tr><th>Fix version:</th><td>tba</td></tr><tr><th>Fix release date:</th><td>tba</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Check with Forge 36.2.30, Minecraft 1.16.5 and Mod version 2.0.0 if the Issue can be confirmed. (Issue cannot be confirmed.)

**Comment by GeheimagentNr1** [comment]
Are you really using Forge?  
Forge version for 1.16.5 is 36.X.X and not 0.200.X.X.

Chunks, that are already generated, are not generated again. These skipped chunks can increase the pre generation rate.

**Comment by chocobear01** [comment]
Hi there! Thank you for the help! I'm sorry for the late reply, I was out of town for a couple of days.

I am using Forge but maybe I am looking in the wrong place or at the wrong number? When clicking the cog/settings icon on the bottom left it says "v. 0.200.1.7". Is there another place you would reccomend checking?

I thought that's what it was at first but even after waiting for it to complete, waiting for it to catch up with how many chunks were generated before, or waiting for the chunk generation rate to slow back down again, it is still no longer creating region files and there is chunk lag when exploring.

**Comment by GeheimagentNr1** [comment]
In default Forge modpacks you can find the Forge version in the left button corner, in this image shown red:

![](https://user-images.githubusercontent.com/20889593/174449492-6917fb91-9137-470d-b9ee-3fff9a55497b.png)
