### ISSUE TITLE
Crash after pregenerating for a ~30 seconds

### ISSUE THREAD

**Issue by addmix** [GeheimagentNr1/WorldPreGenerator#12]
**Versions**
Minecraft Version: 1.18.2
Minecraft Forge Version: v40.1.0
Mod Version: 2.0.1

**Log files**
[crash-2022-06-10_19.49.49-server.txt](https://github.com/GeheimagentNr1/WorldPreGenerator/files/8882929/crash-2022-06-10_19.49.49-server.txt)

**Describe the bug**
Queued pregen with radius of 200, will pregen for 30 seconds or so and then crash the server.

I find it likely to be an incompatability with Terraforged.

**Comment by GeheimagentNr1** [comment]
Please set the "max-tick-time" in the server.properties file to -1 during the pre generation and reset it to 60000, when the pre generation is finished.

https://minecraft.fandom.com/wiki/Server.properties#Java_Edition_3
