### ISSUE TITLE
Pre generation crashes server upon completion when parallel generation is disabled

### ISSUE THREAD

**Issue by Wazbat** [GeheimagentNr1/WorldPreGenerator#13]
**Versions**
Minecraft Version: 1.18.2
Minecraft Forge Version: 40.1.74
Mod Version: 3.0.0

**Log files**
[crash-2022-08-31_23.02.34-server.txt](https://github.com/GeheimagentNr1/WorldPreGenerator/files/9465614/crash-2022-08-31_23.02.34-server.txt)

**Describe the bug**
The server crashes upon finishing generation, after the dimensions have saved. This only happens if parallel generation is disabled, which is the default setting

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the mod
2. Start a generation job, for example with 10 chunks as a radius
3. Wait for it to finish
4. Server crashes

**Expected behaviour**
Server to not crash when generating without parallel generation enabled

**Additional context**
I'm not super experienced with java, but I believe the issue lies in [this file](https://github.com/GeheimagentNr1/WorldPreGenerator/blob/master_1.18.2/src/main/java/de/geheimagentnr1/world_pre_generator/elements/queues/tasks/pregen/PregenTask.java#L234), specifically in the final `shutdown` method

The `executor` property is only assigned if `ServerConfig.isRunParallel()` is true, and there are checks for this in the `generate` method, however there are no checks for it in the final `shutdown` method

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Critical Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>3.0.1</td></tr><tr><th>Fix release date:</th><td>01.09.2022</td></tr></tbody></table>

**Issue confirmed for:**

* Multiple version

**TODOs:**

*   [x] Implementing fix

**Comment by GeheimagentNr1** [comment]
I fixed the issue with version 3.0.1.
Thank you for reporting the issue.

**Comment by Wazbat** [comment]
Thanks for the quick fix!
