### ISSUE TITLE
Using World Pre Gen crashes world 

### ISSUE THREAD

**Issue by Zelioth** [GeheimagentNr1/WorldPreGenerator#14]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.1.34
Mod Version: 3.0.1

[crash-2022-10-08_00.55.32-server.txt](https://github.com/GeheimagentNr1/WorldPreGenerator/files/9738509/crash-2022-10-08_00.55.32-server.txt)

We just opened our second server for our mod pack. the world is new and no players are online besides myself and another builder but we are just at spawn. I set world pregen it lagged badly for a little bit started then crashed with this crash log.

**Comment by GeheimagentNr1** [comment]
Please set the max-tick-time in the server.properties file to -1 and set it back to, 60000 after the pre generation.
https://minecraft.fandom.com/wiki/Server.properties#Java_Edition_3

**Comment by Gbergz** [comment]
Have this issue aswell, with `max-tick-time: -1` it just stalls forever and nothings more happens even after an hour of waiting.

Crash-report: (had max-tick-time set to 900,000 this one)
https://gist.github.com/Gbergz/2b2e79d7a2b0128a25458850a102f874

(Edit: This is in a modpack, ofcourse. It could be something else causing it.)

**Comment by GeheimagentNr1** [comment]
In my tests, everything worked well. In the chat and the logs, the progress was shown without any issues.

What size are you trying to pre generate?  
Are you using parallel pre generation?  
What modpack are you using?

**Comment by Gbergz** [comment]
TNP Limitless 6
315 size about 10k all directions.
Stuck and crashes after about 65% completion.

**Comment by Zelioth** [comment]
Friends United 1.19.2 Forge 43.1.34
Generating from spawn so 
pregen gen [Dim] [cords(Spawn location)] 100 radious 

that is the command I run and it'll lag out and crash about 50% of the time. or 
crash on a behind tick amount

**Comment by GeheimagentNr1** [comment]
I tested again, with "Friends United" 1.19.2, Forge 43.2.1, Mod version 3.0.1 and a single player world and could not find any issues or crashes.
