### ISSUE TITLE
Only two cores being used by mod.

### ISSUE THREAD

**Issue by SK-Crow** [GeheimagentNr1/WorldPreGenerator#15]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.2.0
Mod Version: 1.19.2-3.0.1

**Log files**
Please append the log, debug-log and if available the crash-log files.

**Describe the bug**
Only two cores / 4 threads are being used during generation.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use default settings (Core count set to 0 which should be all cores)
2. Start a world render
3. Notice that only two cores are being used.

**Expected behaviour**
Expected that with value set to 0, all cores/threads would be used for generation.

**Screenshots**
![image](https://user-images.githubusercontent.com/1341176/236586196-e8531229-ccc3-435f-9dfb-f9261d0c753d.png)

**Additional context**
Not sure if I'm misunderstanding the documentation.  Mod is working well, but it could be 3x as fast on this hardware.  Did you have different results?  Perhaps something has to be enabled on Java's end to allow multi-core past two?

**Comment by GeheimagentNr1** [comment]
The "parallel" generation is more a semi parallel pre-generation than a parallel pre-generation. It only generates the pre-generation "tasks" in parallel. The generation itself is done the Minecraft way and that is done only by the many thread one after another. I updated the mod and clarified it in the description.
