### ISSUE TITLE
Nether pregen stops at 56%

### ISSUE THREAD

**Issue by siryampy** [GeheimagentNr1/WorldPreGenerator#16]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 1.19.2
Mod Version: 1.19.2-3.0.1

**Log files**
Please append the log, debug-log and if available the crash-log files.

**Describe the bug**
When pregening the nether world it gets to 56% and the server just infinitely hangs. Server then needs to be manually stopped and started.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run /pregen gen minecraft:the_nether start -10 -6 312 false
2. wait
3. stops at 56% and server freezes/hangs

**Expected behaviour**
For it to pregen to 100%

**Screenshots**
Please see log attached

**Additional context**
We've been using your mod for a few days now with no issues, we have pregened the overworld and the end with no issues. Tick is set to -1 as well.
[latest.log](https://github.com/GeheimagentNr1/WorldPreGenerator/files/12290551/latest.log)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Further information requested</td></tr><tr><th>Issue type:</th><td>tba</td></tr><tr><th>Fix type:</th><td>tba</td></tr><tr><th>Fix version:</th><td>tba</td></tr><tr><th>Fix release date:</th><td>tba</td></tr></tbody></table>

**Issue confirmed for:**

**None**

**TODOs:**

None

**Comment by GeheimagentNr1** [comment]
From the log, it seems more like a crash because of a Hanging entity in the nether:

```
\[08Aug2023 11:16:01.973\] \[Worker-Main-2/ERROR\] \[net.minecraft.world.entity.decoration.HangingEntity/\]: Hanging entity at invalid position: BlockPos{x=-28, y=104, z=92}  
\[08Aug2023 11:16:02.402\] \[Worker-Main-11/ERROR\] \[net.minecraft.Util/\]: Caught exception in thread Thread\[Worker-Main-11,4,main\]  
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.DataLayer.m\_62560\_(int, int, int)" because "$$2" is null  
```
Did you try restarting the server after this issue occurred?
The pregeneration continues at the same point, where it were stopped before the restart.
Hopefully this should fix the issue.
