### ISSUE TITLE
Invalid argument when running /pregen start

### ISSUE THREAD

**Issue by kayshrieve** [GeheimagentNr1/WorldPreGenerator#2]
**Versions**
Minecraft Version: 1.16.5
Minecraft Forge Version: 36.2.1
Mod Version: 1.16.5 2.0.0

**Log files**
n/a

**Describe the bug**
When running /pregen start, any time a number is put in place for the x y coordinate, it shows as an invalid argument & in return, will not run. All other commands work, it is only /pregen start where this occurs. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open minecraft chat / console
2. Type /pregen start x y radius minecraft:world
3. Enter

**Expected behaviour**
Expected for the command to run, show no invalid arguments, and begin to pregenerate chunks in MC.
![issue log](https://user-images.githubusercontent.com/64279595/127488483-f11f513b-9aa7-4c09-ba75-c6d23f79149d.png)
![issue2](https://user-images.githubusercontent.com/64279595/127488529-6f2d4218-5d97-4bb3-9e24-056e7c8c914c.png)

**Screenshots**
Screenshots of the command as written in the description on forge, as well as the feedback given attached. 
**Additional context**
We have reinstalled the mod, client and server side, and just server side, as well as having multiple people try on multiple machines to get this working before submitting an issue as a litmus test

**Comment by GeheimagentNr1** [comment]
Is the Mod installed on the server and the client side?

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>none</td></tr><tr><th>Fix type:</th><td>tba.</td></tr><tr><th>Fix version:</th><td>tba.</td></tr><tr><th>Fix release date:</th><td>tba.</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Test in Minecraft 1.16.5 and Mod 2.0.0 on server and client side with a server.

**Comment by GeheimagentNr1** [comment]
In my tests, it does work, with the mod installed on the server and the client side.

![](https://user-images.githubusercontent.com/20889593/127501858-ee319272-1ef7-4c62-be1f-715b574a079f.png)

The only case, in which I can regenerate the issue, is, if the mod is not installed on the client side.

![](https://user-images.githubusercontent.com/20889593/127502551-2b2ee54d-3a83-4251-8d7c-467ee7d4e698.png)
