### ISSUE TITLE
Config rewrite issue

### ISSUE THREAD

**Issue by Cobbert** [GeheimagentNr1/WorldPreGenerator#3]
**Versions**
Minecraft Version: [1.16.5]
Minecraft Forge Version: [e.g. 36.2.6]
ATM6 Mod Version: [1.8.7]

Server Specs:
Intel Xeon D-1521 - 32GB DDR4 ECC 2133MHz - 2x HDD SAS 4TB Enterprise Class RAID

**Log files**
No crashing, will post logs if needed

**Describe the bug**
Changes to atm6/world/serverconfig/world_pre_generator-server.toml are changed back to default on server reboot and changes take no effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change world_pre_generator-server.toml to allow parallel generation
2. restart server to apply effects of config changes
3. reopen world_pre_generator-server.toml after server starts, changes have been reverted
4. No aparent output in console window and generation only goes around 1-10 chunks/s

**Expected behaviour**
Changes to world_pre_generator-server.toml to have an effect to speed up pregen.

**Screenshots**

**Additional context**

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Investigations running</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>tba</td></tr><tr><th>Fix version:</th><td>tba</td></tr><tr><th>Fix release date:</th><td>tba</td></tr></tbody></table>

**Issue confirmed for:**

none

**TODOs:**

*    [x]  Check with Minecraft 1.16.5, and current Forge version, if the error can be reproduced.

**Comment by GeheimagentNr1** [comment]
I could not reproduce the error.  
But with other mods (mine too) I had the issue, if I changed the config while the server is running, the config was reset to the default config.  
Please try to stop the server, change the config and then restart the config again.

**Comment by Cobbert** [comment]
Confirmed that shutting down the server and then making my changes saves the changes and puts them into effect.
