### ISSUE TITLE
Crash on preloading

### ISSUE THREAD

**Issue by SaphieNyako** [GeheimagentNr1/WorldPreGenerator#4]
**Versions**
Minecraft Version: 1.16.5
Minecraft Forge Version: 36.2.8
Mod Version: 2.0

**Log files**

[crash-2021-10-31_12.22.46-server.txt](https://github.com/GeheimagentNr1/WorldPreGenerator/files/7448892/crash-2021-10-31_12.22.46-server.txt)

**Describe the bug**
Around 12% it crashes, every world I tried has this issue

Any ideas what the cause could be?

**Comment by GeheimagentNr1** [comment]
Do you have parallel generation activated?  
If yes, try setting "max-tick-time" in the server.properties file to -1.  
https://minecraft.fandom.com/wiki/Server.properties

**Comment by SaphieNyako** [comment]
Yes that worked. Thanks
