### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by mensinda** [GeheimagentNr1/WorldPreGenerator#6]
I have ported `WorldPreGenerator` to fabric (mostly for my personal use): 

- https://github.com/mensinda/WorldPreGenerator/tree/fabric_1.18
- ~https://github.com/mensinda/WorldPreGenerator/releases/tag/1.18-fabric-2.0.0~

Normally I would directly open a PR, but for that, I would need a target branch for fabric (which doesn't exist yet).

Is there any interest in mainlining my fabric port or would you like me to keep it separate? I did my best to keep the git diff to the forge version as minimal as possible.

**Comment by GeheimagentNr1** [comment]
You don't know much about licensing, do you?  
Here is an explanation of the "All rights reserved" licence: https://www.legalzoom.com/articles/the-term-all-rights-reserved-explained

**Comment by mensinda** [comment]
> You don't know much about licensing, do you?

I knew that you are very restricted in what you can do, but I was assuming that it was OK to fork a project and making changes in the fork. Otherwise opening PRs would be pretty much impossible and there is practically very little point in publishing the source code in the first place (which is my intention).

I included a JAR in my release so that it would be easy for you to test my changes. I did **not** put in on curse forge or any other mod portal and I have no intentions of doing so without your permission. I also did **not** advertise my port anywhere (well, I guess besides this issue). I have removed the release, since I am guessing you don't want me to have it up.

So I am sorry if I did not ask for permission before publishing my fork. I basically wanted the functionality of this mod for my personal session to prepare a server world and potentially contribute my changes upstream.

So how do you want to continue this? Do you want me to make my repo private? Is there any interest from your side in mainlining my changes? Can I keep my fork up (with or without a release)?

**Comment by GeheimagentNr1** [comment]
I don't have any interest in Fabric Mods and Fabric Modding.  
If you set the repo to private and only use the mod for private purposes, it's fine with me.

Any distribution is a copyright violation. (https://www.gesetze-im-internet.de/urhg/index.html)

**Comment by mensinda** [comment]
Sad to hear that. I removed the fork.

I would also recommend adding an explicit comment in all your repositories about your stance on this issue (no forking without permission and PRs are not wanted, etc.). This is GitHub where open source collaboration is a core aspect and you can't really turn the fork button of, so...

I would guess that many people won't look at the `LICENSE` file.

Also, it would be nice if you could at least be consistent about your copyright claims (if you care strongly come with the Urheberrechtsgesetz), or does this person have your permission?
- https://github.com/12456600/AutoRestart


Noch einen schönen Abend.
