### ISSUE TITLE
Crashes on Server Startup 

### ISSUE THREAD

**Issue by Tyronadre** [GeheimagentNr1/WorldPreGenerator#8]
Minecraft Version: 1.18.1
Minecraft Forge Version: 39.0.19
Mod Version: 2.0.0

Crashes on Server Startup
[crash-2022-01-14_17.08.20-fml.txt](https://github.com/GeheimagentNr1/WorldPreGenerator/files/7872102/crash-2022-01-14_17.08.20-fml.txt)

**Comment by xxtakuraxx** [comment]
I have the same issue. Crashes single and multiplayer with the "has failed to load correctly" message.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Critical Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>2.0.1</td></tr><tr><th>Fix release date:</th><td>15.01.2022</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft version: 1.18.1  
    Forge version: 39.0.19  
    Mod version:  2.0.0

**TODOs:**

*   [x] Test with Minecraft 1.18.1, Forge 39.0.19, Mod 2.0.0
*   [x] Implementing fix

**Comment by GeheimagentNr1** [comment]
Issue fixed with version 2.0.1
